In [2]:
import numpy as np
import pandas as pd
import pyreadr

data_path = "/data/IDEA_DeFi_Research/Data/Lending_Protocols/Aave/V2/Mainnet/preprocessed_user_market_time/preloaded_4_None/checkpoints/aave_small_longSeq/checkpoint-169150/"
# Load embeddings
embeddings = np.load(f"{data_path}cls_embeddings.npy")
embedding_ids = np.load(f"{data_path}cls_embeddings_row_ids.npy")
data_df = pd.DataFrame(embeddings)
data_df["id"] = embedding_ids
# Load labels (assuming labels file is available)
labels_df = pyreadr.read_r(f"/data/IDEA_DeFi_Research/Data/Lending_Protocols/Aave/V2/Mainnet/id_types.rds")[None]

In [2]:
x_ltm_path = "/data/IDEA_DeFi_Research/Data/Survival_Data/Borrow/X_ltm_seqLen50/"

In [3]:
# Step 1: Merge the two dataframes on 'id'
merged_df = pd.merge(data_df, labels_df, on='id', how='inner')

In [4]:
merged_df.head()

,0,1,2,3,4,5,6,7,8,9,...,992,993,994,995,996,997,998,999,id,type
0,-0.429036,-0.020325,3.4951,-0.055845,0.384405,1.332549,0.532871,-0.562247,-0.502839,0.344566,...,-0.121404,-0.934529,-0.418489,-0.387842,0.397443,0.067066,2.281588,-0.522596,0x3fec3516c8085e089d408562dd3f9ca1bbbc5b0eb4ea...,collateral
1,-0.429036,-0.020325,3.4951,-0.055845,0.384405,1.332549,0.532871,-0.562247,-0.502839,0.344566,...,-0.121404,-0.934529,-0.418489,-0.387842,0.397443,0.067066,2.281588,-0.522596,0x452f5f9b8d503f395a1db08a2bd8f3af937d401d5358...,collateral
2,-0.429036,-0.020325,3.4951,-0.055845,0.384405,1.332549,0.532871,-0.562247,-0.502839,0.344566,...,-0.121404,-0.934529,-0.418489,-0.387842,0.397443,0.067066,2.281588,-0.522596,0x452f5f9b8d503f395a1db08a2bd8f3af937d401d5358...,collateral
3,-0.429036,-0.020325,3.4951,-0.055845,0.384405,1.332549,0.532871,-0.562247,-0.502839,0.344566,...,-0.121404,-0.934529,-0.418489,-0.387842,0.397443,0.067066,2.281588,-0.522596,0x59a33c72e045d762a069ddfe10540ddc1b521cbd27e1...,collateral
4,-0.429036,-0.020325,3.4951,-0.055845,0.384405,1.332549,0.532871,-0.562247,-0.502839,0.344566,...,-0.121404,-0.934529,-0.418489,-0.387842,0.397443,0.067066,2.281588,-0.522596,0x3c07de24894604a8e9fd36be5eda98a8f9fdad794536...,collateral

In [5]:
merged_df.to_csv('~/merged_df_ltm_seqLen50.csv', index=False)

In [6]:
# Step 2: Filter to just "borrow" transactions
borrow_df = merged_df[merged_df["type"] == "borrow"]

# Drop the 'type' column since it's no longer needed
borrow_embeddings_df = borrow_df.drop(columns=['type'])

# Inspect the result
print(borrow_embeddings_df.head())

            0         1         2         3         4         5         6  \
34   0.801315 -0.803961 -1.086387  0.687823  0.908221 -0.888263 -0.873841
36   0.801315 -0.803961 -1.086387  0.687823  0.908221 -0.888263 -0.873841
38   0.130179 -1.592879  1.519559 -0.142015 -1.159098  1.137712 -0.569533
40   0.063832 -1.610488  1.868482 -0.178194 -1.277114  1.181953  0.252833
203  0.801315 -0.803961 -1.086387  0.687823  0.908221 -0.888263 -0.873841

            7         8         9  ...      3991      3992      3993  \
34  -0.135373 -0.069406  0.118456  ...  0.682567 -0.560307  0.796460
36  -0.135373 -0.069406  0.118456  ...  0.682567 -0.560307  0.796460
38   1.400236  1.189970 -1.946008  ... -0.308397  1.664098 -0.036695
40   1.481617  1.560257 -2.003878  ... -0.242732  1.853565 -0.136588
203 -0.135373 -0.069406  0.118456  ...  0.682567 -0.560307  0.796460

         3994      3995      3996      3997      3998      3999  \
34  -0.873366 -0.330756  1.449331  0.560098 -1.655826  0.366614
36  -0.873366 -0.330756  1.449331  0.560098 -1.655826  0.366614
38  -0.191208  0.756961 -1.059880 -1.159152  1.616540  0.904398
40  -0.207249  0.937260 -1.393891 -1.199464  1.587506  0.953645
203 -0.873366 -0.330756  1.449331  0.560098 -1.655826  0.366614

                                                    id
34   0x6108df238ef0c8ef508de06628dab9eca646b2eeff77...
36   0x6108df238ef0c8ef508de06628dab9eca646b2eeff77...
38   0x0ee78a520958780577a64993f01050cc32e80bd0bad9...
40   0x0ee78a520958780577a64993f01050cc32e80bd0bad9...
203  0x8c40adab53958c9be49fa89fd31fd245aa4b8fce4b94...

[5 rows x 4001 columns]

In [ ]:
pyreadr.write_rds(f"{x_ltm_path}/X.rds", borrow_embeddings_df)

/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['-0.06747501343488693' '-0.06747501343488693' '-0.5246846079826355' ...
 '-0.28996092081069946' '-0.2880224883556366' '-0.9496933221817017']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['-0.38766270875930786' '-0.38766270875930786' '-0.5026392936706543' ...
 '-0.26410895586013794' '-0.21697528660297394' '0.021113287657499313']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['-0.44926905632019043' '-0.44926905632019043' '0.19931600987911224' ...
 '1.0874778032302856' '0.7653017044067383' '0.6125926971435547']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['-0.852811336517334' '-0.852811336517334' '1.38036048412323' ...
 '0.7899585962295532' '0.9746363162994385' '2.2131199836730957']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.6260338425636292' '0.6260338425636292' '-0.6838358640670776' ...
 '-0.8615468144416809' '-0.8245899081230164' '-1.1498260498046875']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['-0.1413397490978241' '-0.1413397490978241' '-0.8758789300918579' ...
 '-1.1907622814178467' '-1.0459269285202026' '-1.653196930885315']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.49735549092292786' '0.49735549092292786' '0.5514835715293884' ...
 '0.9960476756095886' '0.8197208642959595' '0.3886352479457855']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.18957366049289703' '0.18957366049289703' '0.5437114834785461' ...
 '0.8884824514389038' '1.2133313417434692' '1.0230594873428345']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.40631169080734253' '0.40631169080734253' '-1.2945916652679443' ...
 '-0.9324285387992859' '-1.2491495609283447' '-1.1146153211593628']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['1.228261947631836' '1.228261947631836' '-0.9337683916091919' ...
 '-1.1722705364227295' '-0.7020248770713806' '-0.8165175318717957']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['-0.105472132563591' '-0.105472132563591' '-0.4156511723995209' ...
 '-0.9614733457565308' '-0.646561324596405' '-0.8532600998878479']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['-0.020525909960269928' '-0.020525909960269928' '0.06130201369524002' ...
 '-0.6844494938850403' '-0.6173287630081177' '-0.4453800916671753']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.9591914415359497' '0.9591914415359497' '-0.4455445110797882' ...
 '0.502230167388916' '-0.12790492177009583' '0.2686816155910492']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['1.0905896425247192' '1.0905896425247192' '-1.3154324293136597' ...
 '-1.1761773824691772' '-1.5064336061477661' '-1.162514328956604']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.00708993524312973' '0.00708993524312973' '-1.1636085510253906' ...
 '-0.44591960310935974' '-0.5903657674789429' '-0.6623100638389587']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))
/home/greena12/.conda/envs/greena12/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.25082364678382874' '0.25082364678382874' '-0.23638135194778442' ...
 '-0.5884767174720764' '-0.924196720123291' '-0.4540259540081024']' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  pd_series.loc[pd.notnull(pd_series)] = pd_series.loc[pd.notnull(pd_series)].apply(lambda x: str(x))